Repository glomfigli/glomfig, pull requests merged in 2023-03, with the labels that each got.

#14 Set up database
  package-lock.json
  package.json
  server/database.ts
  server/index.ts
  server/models/User.ts
Labels: enhancement

#15 Enchanced development environment
  package-lock.json
  package.json
Labels: enhancement, meta

#19 routes updated
  server/src/controllers/user-controller.ts
  server/src/routes/user-routes.ts
Labels: enhancement

#21 Add .nvmrc
  .nvmrc
  docker-compose.yml
Labels: enhancement, meta

#23 Store password hashes
  server/package-lock.json
  server/package.json
  server/src/controllers/user-controller.ts
  server/src/routes/user-routes.ts
Labels: enhancement

#28 Perseist database in a volume between builds
  docker-compose.yml
Labels: meta

#30 Root cleanup
  .editorconfig
  .github/workflows/lint.yml
  .gitignore
  client/.eslintignore
  client/.gitignore
  client/.nvmrc
  package-lock.json
  package.json
  server/.gitignore
  server/.nvmrc
Labels: enhancement, meta

#32 Implement session functionality
  docker-compose.yml
  server/package-lock.json
  server/package.json
  server/src/config.ts
  server/src/controllers/session-controller.ts
  server/src/controllers/user-controller.ts
  server/src/index.ts
  server/src/middleware/authentication.ts
  server/src/models/Session.ts
  server/src/routes/session-routes.ts
Labels: enhancement

#33 Provide more encapsulation and abstraction
  docs/architecture/server.md
  server/.eslintrc.json
  server/src/controllers/ConfigController.ts
  server/src/controllers/Controller.ts
  server/src/controllers/SessionController.ts
  server/src/controllers/UserController.ts
  server/src/controllers/config-controller.ts
  server/src/controllers/session-controller.ts
  server/src/controllers/user-controller.ts
  server/src/index.ts
  server/src/models/Config.ts
  server/src/models/IConfig.ts
  server/src/models/IModel.ts
  server/src/models/ISession.ts
  server/src/models/IUser.ts
  server/src/models/Session.ts
  server/src/models/User.ts
  server/src/models/mongo/Config.ts
  server/src/models/mongo/Session.ts
  server/src/models/mongo/User.ts
  server/src/repositories/IRepository.ts
  server/src/repositories/mongo/MongoRepository.ts
  server/src/routes/config-routes.ts
  server/src/routes/configRoutes.ts
  server/src/routes/session-routes.ts
  server/src/routes/sessionRoutes.ts
  server/src/routes/user-routes.ts
  server/src/routes/userRoutes.ts
Labels: enhancement

#35 Server architecture docs
  README.md
  docs/architecture/server-architecture.md
  docs/assets/server-architecture-controllers.svg
  docs/assets/server-architecture-models.svg
  docs/assets/server-architecture-package-overview.svg
  docs/assets/server-architecture-repositories.svg
  docs/assets/server-architecture.puml
Labels: documentation
